workers_dev = true
type = "javascript"
name = "beth-price-feed-dev"
account_id = ""

[vars]
CHAIN_ID = 1
ENV = "development"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""

[build]
command = "npm run build"

[build.upload]
format = "service-worker"


[env.staging]
workers_dev = false
name = "beth-price-feed-staging"
route = ""
zone_id = ""

[env.staging.vars]
CHAIN_ID = 1
ENV = "staging"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""

[env.production]
workers_dev = false
name = "beth-price-feed"
route = ""
zone_id = ""

[env.production.vars]
CHAIN_ID = 1
ENV = "production"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""