workers_dev = true
type = "javascript"
name = "beth-price-feed-dev"
account_id = ""

[vars]
ENV = "development"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""
DEVIATION_BLOCK_OFFSETS = '[44800,6400,250]'
BETH_RATE_LIMITS = '{"deviations":[10,5,2]}'
BETH_PRICE_LIMITS = '{"maxValue":3100,"minValue":"3000","deviations":[20,15,5]}'
STETH_RATE_LIMITS = '{"maxValue":1.05,"minValue":0.95,"deviations":[20,10,0.003]}'
ETH_PRICE_LIMITS = '{"maxValue":4000,"minValue":2500,"deviations":[50,25,15]}'

[build]
command = "npm run build"

[build.upload]
format = "service-worker"


[env.staging]
workers_dev = false
name = "beth-price-feed-staging"
route = ""
zone_id = ""

[env.staging.vars]
ENV = "staging"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""

[env.production]
workers_dev = false
name = "beth-price-feed"
route = ""
zone_id = ""

[env.production.vars]
ENV = "production"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""